project:
  type: website

website:
  title: "E155 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: labs\labs-overview.qmd
        text: Labs
      - href: blog.qmd
        text: Blog
      - href: resources.qmd
        text: Resources

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



